version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: u825482285_kodoninja
      POSTGRES_USER: u825482285_kodoninja
      POSTGRES_PASSWORD: Cmyk.7625.KNkn
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  my_network:
    driver: bridge

volumes:
  db_data: